apiVersion: v1
kind: Pod
metadata:
  name: gpu-workload-pod
  labels:
    app: ml-training
    workload-type: gpu
spec:
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - name: ml-container
    image: nginx:1.21
    ports:
    - containerPort: 80
