apiVersion: v1
kind: Pod
metadata:
  name: selector-scheduling-pod
  labels:
    app: nginx
    tier: frontend
spec:
  nodeSelector:
    disktype: ssd
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  containers:
  - name: nginx-container
    image: nginx:1.21
    ports:
    - containerPort: 80
