apiVersion: v1
kind: Pod
metadata:
  name: manual-scheduling-pod
  labels:
    app: nginx
    tier: frontend
    environment: production
spec:
  nodeName: worker-node-1  
  containers:
  - name: nginx-container
    image: nginx:1.21
    ports:
    - containerPort: 80
      protocol: TCP

