apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    app: init-demo
spec:
  initContainers:
  - name: init-setup
    image: busybox:1.35
    command: ['sh', '-c']
    args:
    - |
      echo "Initializing application..."
      echo "Waiting for dependencies..."
      sleep 5
      echo "Init container completed successfully"
  containers:
  - name: main-app
    image: nginx:1.14.2
    ports:
    - containerPort: 80
