apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc # name of the replication controller
  labels:
    app: demo
spec: 
  replicas: 3
  template:
    metadata:
      name: nginx # name of the pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx # name of the container
        image: nginx  
        ports:
        - containerPort: 80